NUM_GENERATIONS = 20
NUM_MAX_LAYERS = 4
SAMPLERATE = 96000
DURATION = 5 
SHUFFLE_PEDALBOARD = True 

ONLY_REVERB = False # Enabled
USING_DYNAMIC_TRIM = True # Disable me to use the whole audio file
USING_PAD_AUDIO = True
USING_RANDOM_FLIP_PRE = True # Disabled
USING_TIME_STRETCH = True
USING_PITCH_SHIFT = True
USING_LPF_PRE = True
USING_OTT = True
USING_DISTORTION = False
USING_DRIVER = True
USING_BITCRUSH = True
USING_LPF_POST = True
USING_CHORUS = True
USING_SUPERMASSIVE = True
USING_LIMITER = True
USING_RANDOM_FLIP_POST = True # Disabled

# Minimal Audio
USING_FUSE_COMPRESSOR = True
USING_HYBRID_FILTER = True
USING_RIFT = True
USING_RIFT_FEEDBACK_LITE = True
USING_RIPPLE_PHASER = True
USING_FLEX_CHORUS = True
USING_CLUSTER_DELAY = True
USING_SWARM_REVERB = True
