# Main
NUM_GENERATIONS = 100
SAMPLERATE = 96000
DURATION = 5 
NUM_RIFTS = 4

# Generic
USING_PAD_AUDIO = True
SHUFFLE_PEDALBOARD = True 
USING_RANDOM_FLIP_PRE = True # Disabled
USING_RANDOM_FLIP_POST = False # Disabled
ONLY_REVERB = False # Enabled
USING_DYNAMIC_TRIM = True # Disable me to use the whole audio file
USING_TIME_STRETCH = True
USING_PITCH_SHIFT = True

# FX 
USING_LPF_PRE = True
USING_OTT = True
USING_DISTORTION = True
USING_DRIVER = True
USING_BITCRUSH = True
USING_LPF_POST = True
USING_CHORUS = True
USING_SUPERMASSIVE = False
USING_LIMITER = True

# Minimal Audio
USING_FUSE_COMPRESSOR = True
USING_HYBRID_FILTER = True
USING_RIFT = True
USING_RIFT_FEEDBACK_LITE = True
USING_RIPPLE_PHASER = True
USING_FLEX_CHORUS = True
USING_CLUSTER_DELAY = True
USING_SWARM_REVERB = True
