NUM_GENERATIONS = 20
NUM_MAX_LAYERS = 4
SAMPLERATE = 96000
DURATION = 5 
SHUFFLE_PEDALBOARD = True 

ONLY_REVERB = False # Enabled
USING_DYNAMIC_TRIM = False # Disable me to use the whole audio file
USING_PAD_AUDIO = True
USING_RANDOM_FLIP_PRE = False # Disabled
USING_TIME_STRETCH = False
USING_PITCH_SHIFT = False
USING_LPF_PRE = False
USING_OTT = False
USING_DISTORTION = False
USING_DRIVER = False
USING_BITCRUSH = False
USING_LPF_POST = False
USING_CHORUS = False
USING_SUPERMASSIVE = False
USING_LIMITER = False
USING_RANDOM_FLIP_POST = False # Disabled

# Minimal Audio
USING_FUSE_COMPRESSOR = True
USING_HYBRID_FILTER = True
USING_RIFT = True
USING_RIFT_FEEDBACK_LITE = True
USING_RIPPLE_PHASER = True
USING_FLEX_CHORUS = True
USING_CLUSTER_DELAY = True
USING_SWARM_REVERB = True
